services:
  postgres:
    image: 'postgres:bullseye'
    container_name: 'game-db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  game-server:
    image: 'game-server'
    container_name: 'game-server'
    environment:
      POSTGRES_HOST: game-db
    ports:
      - '8080:8080'
    build:
      dockerfile: Dockerfile

volumes:
  postgres-data: