services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
